apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress-proxies
spec:
  type: ingress 
  replicas: 2
  proxyClass: prod
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: prod
spec:
  statefulSet:
    pod:
      tailscaleContainer:
         env:
         - name: TS_DEBUG_FIREWALL_MODE
           value: "iptables"