name: Build and Release [windows]

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Windows build cmd
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build ./cmd/...

    - name: Windows build tests
      env:
        GOOS: windows
        GOARCH: amd64
      run: for d in $(go list -f '{{if .TestGoFiles}}{{.Dir}}{{end}}' ./... ); do (echo $d; cd $d && go test -c ); done

    - name: Compute Tag
      shell: bash
      run: echo "tag=${git rev-parse --short HEAD}" >> $GITHUB_ENV

    - name: Create Zip Release
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        filename: "tailscale-${{ env.tag }}.zip"
        path: "./cmd/*"
    
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "${{ env.tag }}"
        prerelease: false
        title: Tailscale
        files: "tailscale-${{ env.tag }}.zip"
