name: "integration-vms"

on:
  # # NOTE(Xe): uncomment this region when testing the test
  # pull_request:
  #   branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  experimental-linux-vm-test:
    # To set up a new runner, see tstest/integration/vms/runner.nix
    runs-on: [ self-hosted, linux, vm_integration_test ]

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Download VM Images
        run: go test ./tstest/integration/vms -run-vm-tests -run=Download -timeout=60m
        env:
          XDG_CACHE_HOME: "/var/lib/ghrunner/cache"

      - name: Run VM tests
        run: go test ./tstest/integration/vms -v -run-vm-tests
        env:
          TMPDIR: "/tmp"
          XDG_CACHE_HOME: "/var/lib/ghrunner/cache"

      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                "text": "${{ job.status }}: ${{ github.workflow }} <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ env.COMMIT_DATE }} #${{ env.COMMIT_NUMBER_OF_DAY }}> " +
                        "(<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|" + "${{ github.sha }}".substring(0, 10) + ">) " +
                        "of ${{ github.repository }}@" + "${{ github.ref }}".split('/').reverse()[0] + " by ${{ github.event.head_commit.committer.name }}",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure() && github.event_name == 'push'
